docs_dir: docs

# Project information
site_name: Documentaci칩n DAM
site_url: http://localhost:9099
site_description: Documentaci칩m para el m칩dulo de dise침o de interfaces del ciclo formativo DAM
site_author: CIFP Carlos III

# Copyright
copyright: Copyright &copy; 2024 <a href="https://cifpcarlos3.es/es">CIFPP Carlos III</a>.

# Documentation and theme
theme:
  name: 'material'
  logo: 'images/logo-blanco.svg'
  features:
    - toc.follow

# Options
extra:
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'


# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

plugins:
  - search
  - awesome-pages
  - mermaid2
  - glightbox
  - i18n:
      languages:
        es: "Castellano"
      default_language: 'es'



